# Generated by Django 4.1 on 2022-08-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_alter_task_options_rename_complete_task_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_date',
            field=models.DateTimeField(null=True),
        ),
    ]
