# Generated by Django 4.1 on 2022-08-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0004_alter_task_options_alter_task_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_date',
            new_name='task_date',
        ),
    ]
